module.exports = [
    {
        email: 'alam@alam.com',
        password: '12345678',
        display_name: 'Alam',
        dob: '2000-01-01',
        gender:'M',
        orientation: 'Female',
        location: 'Hong Kong',
        key_atr: 'I',
        key_atr_desc: 'Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/alam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'blam@blam.com',
        password: '12345678',
        display_name: 'Blam',
        dob: '1998-01-02',
        gender:'F',
        orientation: 'Male',
        location: 'Hong Kong',
        key_atr: 'N',
        key_atr_desc: 'We have to dare to be ourselves, however frightening or strange that self may prove to be.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/blam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'clam@clam.com',
        password: '12345678',
        display_name: 'Clam',
        dob: '2000-01-03',
        gender:'M',
        orientation: 'Female',
        location: 'Hong Kong',
        key_atr: 'F',
        key_atr_desc: 'The most painful thing is losing yourself in the process of loving someone too much, and forgetting that you are special too.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/clam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'dlam@dlam.com',
        password: '12345678',
        display_name: 'dlam',
        dob: '1998-01-04',
        gender:'F',
        orientation: 'Male',
        location: 'Hong Kong',
        key_atr: 'F',
        key_atr_desc: 'The most painful thing is losing yourself in the process of loving someone too much, and forgetting that you are special too.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/dlam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'elam@elam.com',
        password: '12345678',
        display_name: 'Elam',
        dob: '2000-01-05',
        gender:'M',
        orientation: 'Female',
        location: 'Hong Kong',
        key_atr: 'N',
        key_atr_desc: 'Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/elam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'flam@flam.com',
        password: '12345678',
        display_name: 'Flam',
        dob: '1998-01-06',
        gender:'F',
        orientation: 'Male',
        location: 'Hong Kong',
        key_atr: 'E',
        key_atr_desc: 'Many a book is like a key to unknown chambers within the castle of one’s own self.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/flam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'glam@glam.com',
        password: '12345678',
        display_name: 'Glam',
        dob: '2000-01-07',
        gender:'M',
        orientation: 'Female',
        location: 'Hong Kong',
        key_atr: 'P',
        key_atr_desc: 'Freeing yourself was one thing, claiming ownership of that freed self was another.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/glam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'hlam@hlam.com',
        password: '12345678',
        display_name: 'Hlam',
        dob: '1998-01-08',
        gender:'F',
        orientation: 'Male',
        location: 'Hong Kong',
        key_atr: 'J',
        key_atr_desc: 'He allowed himself to be swayed by his conviction that human beings are not born once and for all on the day their mothers give birth to them, but that life obliges them over and over again to give birth to themselves.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/hlam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'ilam@ilam.com',
        password: '12345678',
        display_name: 'Ilam',
        dob: '2000-01-09',
        gender:'M',
        orientation: 'Female',
        location: 'Hong Kong',
        key_atr: 'F',
        key_atr_desc: 'We are taught you must blame your father, your sisters, your brothers, the school, the teachers - but never blame yourself. It\'s never your fault. ',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/ilam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'jlam@jlam.com',
        password: '12345678',
        display_name: 'Jlam',
        dob: '1998-01-10',
        gender:'F',
        orientation: 'Male',
        location: 'Hong Kong',
        key_atr: 'J',
        key_atr_desc: 'A self is not something static, tied up in a pretty parcel and handed to the child, finished and complete. A self is always becoming.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/jlam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'klam@klam.com',
        password: '12345678',
        display_name: 'Klam',
        dob: '2000-01-11',
        gender:'M',
        orientation: 'Female',
        location: 'Hong Kong',
        key_atr: 'N',
        key_atr_desc: 'The ability to observe without evaluating is the highest form of intelligence.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/klam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'lam@lam.com',
        password: '12345678',
        display_name: 'Lam',
        dob: '1998-01-12',
        gender:'F',
        orientation: 'Male',
        location: 'Hong Kong',
        key_atr: 'I',
        key_atr_desc: 'You are who you are when nobody\'s watching.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/lam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'mlam@mlam.com',
        password: '12345678',
        display_name: 'Mlam',
        dob: '2000-01-13',
        gender:'M',
        orientation: 'Female',
        location: 'Hong Kong',
        key_atr: 'F',
        key_atr_desc: 'Keep your best wishes, close to your heart and watch what happens.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/mlam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'nlam@nlam.com',
        password: '12345678',
        display_name: 'Nlam',
        dob: '1998-01-14',
        gender:'F',
        orientation: 'Male',
        location: 'Hong Kong',
        key_atr: 'T',
        key_atr_desc: 'I envy people that know love. That have someone who takes them as they are.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/nlam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'olam@olam.com',
        password: '12345678',
        display_name: 'Olam',
        dob: '2000-01-15',
        gender:'M',
        orientation: 'Female',
        location: 'Hong Kong',
        key_atr: 'I',
        key_atr_desc: 'My past is everything I failed to be.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/olam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'plam@plam.com',
        password: '12345678',
        display_name: 'Plam',
        dob: '1998-01-16',
        gender:'F',
        orientation: 'Male',
        location: 'Hong Kong',
        key_atr: 'N',
        key_atr_desc: 'It is not for me to judge another man\'s life. I must judge, I must choose, I must spurn, purely for myself. For myself, alone.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/plam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'qlam@qlam.com',
        password: '12345678',
        display_name: 'Qlam',
        dob: '2000-01-17',
        gender:'M',
        orientation: 'Female',
        location: 'Hong Kong',
        key_atr: 'E',
        key_atr_desc: 'A fit, healthy body—that is the best fashion statement.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/qlam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'rlam@rlam.com',
        password: '12345678',
        display_name: 'Rlam',
        dob: '1998-01-18',
        gender:'F',
        orientation: 'Male',
        location: 'Hong Kong',
        key_atr: 'F',
        key_atr_desc: 'The most painful thing is losing yourself in the process of loving someone too much, and forgetting that you are special too.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/rlam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'slam@slam.com',
        password: '12345678',
        display_name: 'Slam',
        dob: '2000-01-19',
        gender:'M',
        orientation: 'Female',
        location: 'Hong Kong',
        key_atr: 'S',
        key_atr_desc: 'I am only one, but I am one. I cannot do everything, but I can do something. And because I cannot do everything, I will not refuse to do the something that I can do.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/slam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'tlam@tlam.com',
        password: '12345678',
        display_name: 'Tlam',
        dob: '1998-01-20',
        gender:'M',
        orientation: 'Female',
        location: 'Hong Kong',
        key_atr: 'T',
        key_atr_desc: 'We don\'t realize that, somewhere within us all, there does exist a supreme self who is eternally at peace.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/tlam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'ulam@ulam.com',
        password: '12345678',
        display_name: 'Lam',
        dob: '2000-01-21',
        gender:'F',
        orientation: 'Male',
        location: 'Hong Kong',
        key_atr: 'N',
        key_atr_desc: 'You cannot be with someone just because you don’t want to hurt him. You have your own happiness to think about.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/ulam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'vlam@vlam.com',
        password: '12345678',
        display_name: 'Vlam',
        dob: '1998-01-22',
        gender:'M',
        orientation: 'Female',
        location: 'Hong Kong',
        key_atr: 'F',
        key_atr_desc: 'To sell your soul is the easiest thing in the world. That\'s what everybody does every hour of his life. If I asked you to keep your soul - would you understand why that\'s much harder?',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/vlam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'wlam@wlam.com',
        password: '12345678',
        display_name: 'Wlam',
        dob: '2000-01-23',
        gender:'F',
        orientation: 'Male',
        location: 'Hong Kong',
        key_atr: 'T',
        key_atr_desc: 'You are a function of what the whole universe is doing in the same way that a wave is a function of what the whole ocean is doing.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/wlam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'xlam@xlam.com',
        password: '12345678',
        display_name: 'Xlam',
        dob: '1998-01-24',
        gender:'M',
        orientation: 'Female',
        location: 'Hong Kong',
        key_atr: 'I',
        key_atr_desc: 'You are -- your life, and nothing else.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/xlam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'ylam@ylam.com',
        password: '12345678',
        display_name: 'Ylam',
        dob: '2000-01-25',
        gender:'F',
        orientation: 'Male',
        location: 'Hong Kong',
        key_atr: 'J',
        key_atr_desc: 'This above all: to thine own self be true.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/ylam.jpg`,
        ig_account: null,
        token: 10
    },
    {
        email: 'zlam@zlam.com',
        password: '12345678',
        display_name: 'Zlam',
        dob: '1998-01-26',
        gender:'M',
        orientation: 'Female',
        location: 'Hong Kong',
        key_atr: 'F',
        key_atr_desc: 'The problem with introspection is that it has no end.',
        extroversion: false,
        introversion: false,
        sensing: false,
        intuition: false,
        thinking: false,
        feeling: false,
        judging: false,
        perceiving: false,
        profile_pic: `/public/images/users/zlam.jpg`,
        ig_account: null,
        token: 10
    }
];